version: '3.8'
services:
  springapp:
    image: layaramchandra/spring-boot-mongo-docker:latest
    ports:
      - 8080:8080
    environment:
      - MONGO_DB_HOSTNAME=mongo
    networks:
     -  springappnetwork
  mongo:
    image: mongo
    volumes:
     - mongodbval:/data/devdb
    networks:
      -  springappnetwork
networks:
   springappnetwork:
volumes:
   mongodbval:
