version: '3.8'
services:
  springboot:
    image: layaramchandra/springmongodbwithsecrets:latest
    restart: always # This will be ignored if we deploy in docker swarm
    container_name: springboot
    secrets:
    - mongodb_password
    - mongodb_username
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=/run/secrets/mongodb_username
    - MONGO_DB_PASSWORD_FILE=/run/secrets/mongodb_password
    ports:
      - 8080:8080
    working_dir: /opt/app
    depends_on:
    - mongo
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
    networks:
    - springappnetwork
  mongo:
    image: mongo
    container_name: springboot-mongo
    secrets:
    - mongodb_password
    - mongodb_username
    environment:
    - MONGO_INITDB_ROOT_USERNAME=/run/secrets/mongodb_username
    - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_password
    volumes:
      - mongodb:/data/db
    restart: always
    networks:
    - springappnetwork
    
volumes:
  mongodb:
    external: true
    
networks:
  springappnetwork:
    external: true

secrets:
  mongodb_password:
    external: true
  mongodb_username:
    external: true
